## Joining Fips Codes
- notebook to join fips codes to the redfin data

In [6]:
import pandas as pd
import addfips

In [15]:
data = pd.read_csv("/Users/ianbyrne/Development/redfin_data/county_market_tracker.tsv", sep="\t")
data["county"] = data["region"].str.split(",").str[0]
data.head()

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,...,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated,county
0,2017-04-01,2017-04-30,30,county,5,170,f,"Morgan County, AL",NaN,Alabama,...,NaN,NaN,NaN,0.020833,0.020833,0.001225,"Decatur, AL",19460.0,2022-01-09 14:29:56,Morgan County
1,2014-12-01,2014-12-31,30,county,5,1457,f,"Hennepin County, MN",NaN,Minnesota,...,0.097744,-0.121909,-0.197220,0.172414,0.034483,-0.033469,"Minneapolis, MN",33460.0,2022-01-09 14:29:56,Hennepin County
2,2018-02-01,2018-02-28,30,county,5,2319,f,"Tulsa County, OK",NaN,Oklahoma,...,0.206004,-0.026139,0.009313,0.479924,0.068277,-0.042568,"Tulsa, OK",46140.0,2022-01-09 14:29:56,Tulsa County
3,2017-08-01,2017-08-31,30,county,5,1448,f,"Crow Wing County, MN",NaN,Minnesota,...,0.200000,-0.050000,NaN,NaN,NaN,NaN,"Brainerd, MN",14660.0,2022-01-09 14:29:56,Crow Wing County
4,2019-05-01,2019-05-31,30,county,5,1586,f,"Tate County, MS",NaN,Mississippi,...,NaN,NaN,NaN,0.000000,-0.111111,-0.100000,"Memphis, TN",32820.0,2022-01-09 14:29:56,Tate County

In [16]:
row = dict(data.iloc[0])

In [19]:
af = addfips.AddFIPS()
af.add_county_fips(row, county_field="county", state_field="state_code")

{'period_begin': '2017-04-01',
 'period_end': '2017-04-30',
 'period_duration': 30,
 'region_type': 'county',
 'region_type_id': 5,
 'table_id': 170,
 'is_seasonally_adjusted': 'f',
 'region': 'Morgan County, AL',
 'city': nan,
 'state': 'Alabama',
 'state_code': 'AL',
 'property_type': 'All Residential',
 'property_type_id': -1,
 'median_sale_price': 120500.0,
 'median_sale_price_mom': -0.0766283524904214,
 'median_sale_price_yoy': -0.1070766950722489,
 'median_list_price': 147900.0,
 'median_list_price_mom': 0.0064647839401157,
 'median_list_price_yoy': 0.0963676797627872,
 'median_ppsf': 75.84543430871616,
 'median_ppsf_mom': 0.0536285561399878,
 'median_ppsf_yoy': 0.0292133261955098,
 'median_list_ppsf': 79.18695699066473,
 'median_list_ppsf_mom': 0.0107450383331553,
 'median_list_ppsf_yoy': 0.0154056744862027,
 'homes_sold': 106.0,
 'homes_sold_mom': -0.1092436974789915,
 'homes_sold_yoy': -0.1311475409836065,
 'pending_sales': 48.0,
 'pending_sales_mom': 0.0,
 'pending_sales_yoy': -0.0588235294117647,
 'new_listings': 140.0,
 'new_listings_mom': 0.1965811965811965,
 'new_listings_yoy': 0.0769230769230768,
 'inventory': 439.0,
 'inventory_mom': 0.0681265206812651,
 'inventory_yoy': -0.142578125,
 'months_of_supply': 4.1,
 'months_of_supply_mom': 0.5999999999999996,
 'months_of_supply_yoy': -0.1000000000000005,
 'median_dom': 101.0,
 'median_dom_mom': -28.0,
 'median_dom_yoy': -10.0,
 'avg_sale_to_list': 0.9609138541637946,
 'avg_sale_to_list_mom': 0.0093464187806917,
 'avg_sale_to_list_yoy': 0.0050581332225047,
 'sold_above_list': 0.0943396226415094,
 'sold_above_list_mom': -0.0317107975265577,
 'sold_above_list_yoy': -0.0695948035879987,
 'price_drops': nan,
 'price_drops_mom': nan,
 'price_drops_yoy': nan,
 'off_market_in_two_weeks': 0.0208333333333333,
 'off_market_in_two_weeks_mom': 0.0208333333333333,
 'off_market_in_two_weeks_yoy': 0.0012254901960784,
 'parent_metro_region': 'Decatur, AL',
 'parent_metro_region_metro_code': 19460.0,
 'last_updated': '2022-01-09 14:29:56',
 'county': 'Morgan County',
 'fips': '01103'}